all:
  children:
    orange_pi:
      hosts:
        orange-pi:
          ansible_host: 192.168.1.100  
          ansible_user: pi            
          ansible_ssh_private_key_file: /tmp/ssh_key 
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'  